### ISSUE TITLE
need support '.option arch' directive (https://reviews.llvm.org/D123515) to enable linux 6.3 Zbb optimizations?

### ISSUE THREAD

**Issue by enh-google** [google/android-riscv64#63] opened 2023-02-27 20:48 UTC
https://lore.kernel.org/all/20230117122447.y6tdsmsxqdwf76ri@orel/ claims that we need https://reviews.llvm.org/D123515 to be able to compile the new Zbb routines with clang. if that's actually true (?), we should see about shepherding the llvm patch in...

**Comment by asb** [comment] 2023-03-13 09:43
Thanks for catching that there seems to be a real-world user for .option arch (an important one at that!) which is seemingly having issues due to LLVM's current lack of support. Please do bring these things up on the LLVM issue tracker of the patch review as appropriate - it really helps to focus review effort.

**Comment by kito-cheng** [comment] 2023-03-13 09:54
FYI: My (SiFive) colleagues also told me vector implementation in kernel might also require `.option arch` too.

**Comment by appujee** [comment] 2023-03-15 17:23
[jrtc27](https://reviews.llvm.org/p/jrtc27/) commented:

> For Zbb support *in the Linux kernel for its hand-written assembly routines*. Zbb works in Clang/LLVM today, and you can get it with -march=...zbb..., whether for compiler-generated code or hand-written assembly.

**Comment by enh-google** [comment] 2023-03-15 17:28
we use the same clang to compile our kernels, though, so we still need this before we can speed up our kernels.

(but, yes, if you want to flip the switch in the build system today [and eventually in the compiler driver], sgtm!)

**Comment by adelva1984** [comment] 2023-05-10 15:38
Confirmed this 'as' feature is needed for both KERNEL_ZBB and the vector patchset. Kernel ZBB isn't too big a deal for now, but without this feature for vector, kernel save/restore won't be enabled.

**Comment by appujee** [comment] 2023-06-07 18:26
Merged in upstream and cherry-picked to llvm-android

**Closed by appujee** 2023-06-07 18:26 UTC
