### ISSUE TITLE
lldb server not found

### ISSUE THREAD

**Issue by wzhbest** [google/android-riscv64#129] opened 2023-12-20 06:00 UTC
Based on the experiment of LLDB debugging in Android Studio, it was found that the LLDB server cannot be found for the RISCV architecture. Is there a need for additional support
![lldb](https://github.com/google/android-riscv64/assets/5077253/192f1037-a014-4089-a5be-767f7c0db6e7)

Stack information：
[long_text_2023-12-19-15-40-01 (1).txt](https://github.com/google/android-riscv64/files/13724209/long_text_2023-12-19-15-40-01.1.txt)

The profile cannot find the lldb server either：
![profile](https://github.com/google/android-riscv64/assets/5077253/0832a8f7-f10a-4c98-8e5c-79ebe1bea80a)

**Comment by pirama-arumuga-nainar** [comment] 2023-12-20 17:55
Duplicate fo #21 

NDK r27 will be the first release to have lldb-server for riscv64.  If you want to test, this is currently available in the NDK canary bulds: https://ci.android.com/builds/branches/aosp-master-ndk/grid?legacy=1

**Comment by pirama-arumuga-nainar** [comment] 2023-12-20 17:55
Duplicate of #21

**Closed by pirama-arumuga-nainar** 2023-12-20 17:55 UTC

**Comment by MaoHan001** [comment] 2023-12-21 02:10
> Duplicate of #21
> 
> NDK r27 will be the first release to have lldb-server for riscv64. If you want to test, this is currently available in the NDK canary bulds: https://ci.android.com/builds/branches/aosp-master-ndk/grid?legacy=1

I suppose this might be two separate issues, one with the NDK lacking the lldb-server and the other with the log showing that riscv64 cannot be recognized by getClientABIs/DebugProcessStarter.kt.
2023-12-19 15:37:57,330 [2058581] WARN - getClientABIs - Failed to get abi by name: riscv64
2023-12-19 15:37:57,330 [2058581] INFO - getClientABIs - ABIs supported by app: []
2023-12-19 15:37:57,334 [2058585] INFO - #c.i.e.r.ExecutionUtil - Error running 'app':
LLDB server for architectures [] not found
com.intellij.execution.ExecutionException: LLDB server for architectures [] not found
at com.android.tools.ndk.run.lldb.DebugProcessStarterKt.getDebugProcessStarter(DebugProcessStarter.kt:160)
at com.android.tools.ndk.run.lldb.DebugProcessStarterKt.getDebugProcessStarter(DebugProcessStarter.kt:79)
at com.android.tools.ndk.run.editor.NativeAndroidDebugger.getDebugProcessStarterForNewProcess(NativeAndroidDebugger.java:156)
at com.android.tools.ndk.run.editor.NativeAndroidDebugger.getDebugProcessStarterForNewProcess(NativeAndroidDebugger.java:60)
Even using canary builds with LLDB included doesn't seem to work properly.

**Comment by wzhbest** [comment] 2023-12-22 07:26
Using this [version ](ttps://ci.android.com/builds/branches/aosp-master-ndk/grid?legacy=1)[ttps://ci.android.com/builds/branches/aosp-master-ndk/grid?legacy=1](https://ci.android.com/builds/branches/aosp-master-ndk/grid?legacy=1) for verification, neither lldb nor profile works.

[idea.log](https://github.com/google/android-riscv64/files/13749421/idea.log)

lldb server not found:
![2023-12-22 15-21-03 的屏幕截图](https://github.com/google/android-riscv64/assets/5077253/960285b7-c8d7-4e14-a384-4392d22e4523)
![2023-12-22 15-20-45 的屏幕截图](https://github.com/google/android-riscv64/assets/5077253/ad743a12-3a72-40dc-9799-02358b36f7c1)
 
Please help continue to take a look

**Comment by enh-google** [comment] 2024-01-03 19:04
what does `adb shell getprop | grep ro.product.cpu` show?

**Comment by wzhbest** [comment] 2024-01-10 08:40
please see the result:
![90787D15-CE4C-4f2a-97E0-BF64C06E5B01](https://github.com/google/android-riscv64/assets/5077253/62965111-6909-4caf-82a2-4d3fd5c63564)
