### ISSUE TITLE
Cleanup -march flag in aosp after clang driver has those defaults.

### ISSUE THREAD

**Issue by appujee** [google/android-riscv64#98] opened 2023-06-23 21:16 UTC
e.g., [-march](https://android.googlesource.com/platform/build/soong/+/master/cc/config/riscv64_device.go#32) flag has zbb but clang driver also enables zbb by default after https://reviews.llvm.org/D152729 has landed.

**Comment by enh-google** [comment] 2023-09-12 21:16
dupe of #71

**Closed by enh-google** 2023-09-12 21:16 UTC
